spring:
  application:
    name: camera
server:
  port: 8092

eureka:
  client:
    registry-fetch-interval-seconds: 20
    service-url:
      defaultZone: http://localhost:7777/eureka

camera:
  name: USB PC Camera-168
  step: 45
  fps: 20
  arduino:
    com: COM3
    rete: 115200