spring:
  application:
    name: core
  codec:
    max-in-memory-size: 15MB
server:
  port: 8081

eureka:
  client:
    registry-fetch-interval-seconds: 20
    service-url:
      defaultZone: http://localhost:7777/eureka
